name: Publish to NPM

on:
  push:
    tags: [ 'v*' ]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm run test:coverage
    
    - name: Build package
      run: npm run build
    
    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## Changes in @ai-reviewer/core v${{ steps.get_version.outputs.VERSION }}
          
          📦 Published to NPM: [@ai-reviewer/core@${{ steps.get_version.outputs.VERSION }}](https://www.npmjs.com/package/@ai-reviewer/core/v/${{ steps.get_version.outputs.VERSION }})
          
          ### Installation
          ```bash
          npm install @ai-reviewer/core@${{ steps.get_version.outputs.VERSION }}
          ```
          
          ### Breaking Changes
          - See CHANGELOG.md for details
          
          ### New Features
          - See CHANGELOG.md for details
        draft: false
        prerelease: false
    
    - name: Trigger dependent repos update
      run: |
        # Trigger GitHub Action repo
        curl -X POST \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository_owner }}/ai-reviewer-action/dispatches \
          -d '{"event_type":"core-updated","client_payload":{"version":"${{ steps.get_version.outputs.VERSION }}","tag":"${{ github.ref }}"}}'
        
        # Trigger Jenkins repo
        curl -X POST \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository_owner }}/ai-reviewer-jenkins/dispatches \
          -d '{"event_type":"core-updated","client_payload":{"version":"${{ steps.get_version.outputs.VERSION }}","tag":"${{ github.ref }}"}}'
